function getJobSeekerToken() { return localStorage.getItem("talentSyncToken") || sessionStorage.getItem("talentSyncToken"); }
function getJobSeekerRole() { return localStorage.getItem("talentSyncRole") || sessionStorage.getItem("talentSyncRole"); }
function clearJobSeekerAuthentication() { ["talentSyncToken","talentSyncRole","talentSyncUser"].forEach(key => { localStorage.removeItem(key); sessionStorage.removeItem(key); }); }
function checkJobSeekerAuthentication() { if (!getJobSeekerToken() || getJobSeekerRole() !== "JobSeeker") { clearJobSeekerAuthentication(); window.location.href = "../Authentication/login.html"; return false; } return true; }
async function jobSeekerFetch(url, options = {}) { const headers = new Headers(options.headers || {}); headers.set("Authorization", "Bearer " + getJobSeekerToken()); const response = await fetch(url, { ...options, headers }); if (response.status === 401 || response.status === 403) { clearJobSeekerAuthentication(); window.location.href = "../Authentication/login.html"; throw new Error("Your Job Seeker session is not authorized."); } return response; }
async function jobSeekerError(response, fallback) { try { const data = await response.json(); return data.message || data.title || fallback; } catch { return fallback; } }
function showJobSeekerNotice(message, type = "success") { const box = document.getElementById("pageNotice"); if (!box) return; box.textContent = message; box.className = "notice show " + type; setTimeout(() => box.classList.remove("show"), 4500); }
function escapeJobSeekerHtml(value) { const element = document.createElement("div"); element.textContent = value ?? ""; return element.innerHTML; }
function formatJobSeekerDate(value) { return value ? new Date(value).toLocaleDateString() : "Present"; }
function queryNumber(name) { return Number(new URLSearchParams(location.search).get(name) || 0); }
function setupJobSeekerShell() { document.getElementById("menuButton")?.addEventListener("click", () => document.querySelector(".sidebar")?.classList.toggle("open")); document.getElementById("jobSeekerLogout")?.addEventListener("click", event => { event.preventDefault(); clearJobSeekerAuthentication(); location.href = "../Authentication/login.html"; }); const page = location.pathname.split("/").pop(); document.querySelectorAll(".nav a").forEach(link => { const target = link.getAttribute("href").split("?")[0]; if (target === page || (page === "job-details.html" && target === "jobs.html")) link.classList.add("active"); }); }
document.addEventListener("DOMContentLoaded", setupJobSeekerShell);
