const searchForm = document.getElementById("searchForm");
const clearFilters = document.getElementById("clearFilters");
const keyword = document.getElementById("keyword");
const jobLocation = document.getElementById("jobLocation");
const jobSkill = document.getElementById("jobSkill");
const minScore = document.getElementById("minScore");

document.addEventListener("DOMContentLoaded", function () { if (!checkJobSeekerAuthentication()) return; loadMatchingJobs(); searchForm.addEventListener("submit", event => { event.preventDefault(); loadMatchingJobs(); }); clearFilters.addEventListener("click", () => { searchForm.reset(); loadMatchingJobs(); }); });
async function loadMatchingJobs() { const list = document.getElementById("jobsList"); list.innerHTML = '<div class="card loading">Loading matching jobs...</div>'; const params = new URLSearchParams(); if (keyword.value.trim()) params.set("keyword", keyword.value.trim()); if (jobLocation.value.trim()) params.set("location", jobLocation.value.trim()); if (jobSkill.value.trim()) params.set("skill", jobSkill.value.trim()); if (minScore.value) params.set("minMatchScore", minScore.value); try { const response = await jobSeekerFetch(`/api/job-matching/jobs?${params}`); if (!response.ok) throw new Error(await jobSeekerError(response, "Unable to search jobs.")); const jobs = await response.json(); if (!jobs.length) { list.innerHTML = '<div class="card empty">No jobs match these filters.</div>'; return; } list.innerHTML = jobs.map(job => `<article class="card job-card"><h2>${escapeJobSeekerHtml(job.title)}</h2><p>${escapeJobSeekerHtml(job.companyName)}</p><div class="job-meta"><span>📍 ${escapeJobSeekerHtml(job.location)}</span><span class="score">${Number(job.matchScore).toFixed(2)}% match</span></div><div class="score-bar"><span style="width:${Math.min(100,job.matchScore)}%"></span></div><div class="skill-list">${job.missingSkills.map(skill => `<span class="skill-chip missing">Missing: ${escapeJobSeekerHtml(skill)}</span>`).join("") || '<span class="skill-chip">All required skills matched</span>'}</div><div class="actions" style="margin-top:15px"><a class="button button-primary" href="job-details.html?id=${job.jobId}">View Job</a><span class="badge ${job.alreadyApplied ? "badge-active" : "badge-pending"}">${job.alreadyApplied ? "Applied" : "Open"}</span></div></article>`).join(""); } catch (error) { list.innerHTML = `<div class="card empty">${escapeJobSeekerHtml(error.message)}</div>`; showJobSeekerNotice(error.message, "error"); } }
